### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by pavlukivan** [squizduos/ReadMangaDownloader#10]
При попытке скачать любую главу http://readmanga.me/gintama_/

```
Traceback (most recent call last):
  File "./console.py", line 65, in <module>
    pool = WorkerPool(len(chapters_list)) #лимита на закачку нет
  File "C:\python32\lib\multiprocessing\dummy\__init__.py", line 155, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "C:\python32\lib\multiprocessing\pool.py", line 721, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "C:\python32\lib\multiprocessing\pool.py", line 159, in __init__
    self._repopulate_pool()
  File "C:\python32\lib\multiprocessing\pool.py", line 222, in _repopulate_pool
    w.start()
  File "C:\python32\lib\multiprocessing\dummy\__init__.py", line 75, in start
    threading.Thread.start(self)
  File "C:\python32\lib\threading.py", line 683, in start
    _start_new_thread(self._bootstrap, ())
_thread.error: can't start new thread

```

**Comment by MEXAHOTABOP** [comment]
моя ошибка
когда писал многопоток я скорее всего забыл о столь больших мангах 
создается больше потоков чем виндовый 32битный питон может создать и посему оно крашится
